# The build image
FROM node:lts AS build

ENV NODE_ENV production

ENV PORT=${PORT:-3000}

ENV SERVER_PORT=${SERVER_PORT:-${PORT}} SERVER_ADDRESS=${SERVER_ADDRESS:+0.0.0.0} SERVER_PUBLIC_URI=${SERVER_PUBLIC_URI}

ENV CORS_ACCESS_CONTROL_ALLOW_ORIGIN=${CORS_ACCESS_CONTROL_ALLOW_ORIGIN:-*}

ENV OIDC_PROVIDER_URI=${OIDC_PROVIDER_URI} OIDC_CLIENT_ID=${OIDC_CLIENT_ID} OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET} OIDC_TOKEN_SIGNING_ALG=${OIDC_TOKEN_SIGNING_ALG:-EdDSA}

ENV PRIVATE_JWK={PRIVATE_JWK} PUBLIC_JWK={PUBLIC_JWK}

ENV DLT_RPC_PROVIDER_URL=${DLT_RPC_PROVIDER_URL:-http://***REMOVED***:8545}

WORKDIR /app
RUN chown node.node /app
USER node
RUN echo "registry=http://***REMOVED***:8081/repository/i3m-npm-proxy\n@i3m:registry=http://***REMOVED***:8081/repository/i3m-npm-registry" > .npmrc \
  && npm i --production @i3m/conflict-resolver-service
EXPOSE ${SERVER_PORT}
ENTRYPOINT [ "npx" ]
CMD [ "crs" ]
